class Terminal {
  final String name;
  final String location;
  final double latitude;
  final double longitude;
  final String description;
  final String city;
  final int estimatedPassengers;
  final double rating;
  final String type;
  final String density;

  Terminal({
    required this.name,
    required this.location,
    required this.latitude,
    required this.longitude,
    required this.description,
    required this.city,
    required this.estimatedPassengers,
    required this.rating,
    required this.type,
    required this.density,
  });
}

Terminal findTerminalWithHighestPassengers() {
  if (terminalList.isEmpty) {
    throw Exception("Terminal list is empty");
  }

  Terminal maxPassengerTerminal = terminalList[0];

  for (var terminal in terminalList) {
    if (terminal.estimatedPassengers >
        maxPassengerTerminal.estimatedPassengers) {
      maxPassengerTerminal = terminal;
    }
  }

  return maxPassengerTerminal;
}

final List<Terminal> terminalList = [
  Terminal(
      name: "Terminal Bungurasih",
      location: "Kedungrejo",
      latitude: -7.3503844,
      longitude: 112.7256786,
      description: "Terminal Bungurasih di Kedungrejo, Indonesia.",
      city: "Kedungrejo",
      estimatedPassengers: 8500,
      rating: 4.2,
      type: "A",
      density: "Tinggi"),
  Terminal(
      name: "Terminal Baru Kambang Putih",
      location: "Tuban",
      latitude: -6.8600058,
      longitude: 112.0285418,
      description: "Terminal Baru Kambang Putih di Tuban, Indonesia.",
      city: "Tuban",
      estimatedPassengers: 3500,
      rating: 3.8,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Minak Koncar",
      location: "Lumajang",
      latitude: -8.074577,
      longitude: 113.235583,
      description: "Terminal Minak Koncar di Lumajang, Indonesia.",
      city: "Lumajang",
      estimatedPassengers: 4200,
      rating: 3.5,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Tawang Alun",
      location: "Jember",
      latitude: -8.1984769,
      longitude: 113.6300681,
      description: "Terminal Tawang Alun di Jember, Indonesia.",
      city: "Jember",
      estimatedPassengers: 5800,
      rating: 4.0,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Babat",
      location: "Bedahan",
      latitude: -7.0986083,
      longitude: 112.190762,
      description: "Terminal Babat di Bedahan, Indonesia.",
      city: "Bedahan",
      estimatedPassengers: 2100,
      rating: 3.2,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Rajekwesi",
      location: "Bojonegoro",
      latitude: -7.1660882,
      longitude: 111.8962136,
      description: "Terminal Rajekwesi di Bojonegoro, Indonesia.",
      city: "Bojonegoro",
      estimatedPassengers: 3800,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Gendingan",
      location: "Ngawi",
      latitude: -7.375661,
      longitude: 111.2269554,
      description: "Terminal Gendingan di Ngawi, Indonesia.",
      city: "Ngawi",
      estimatedPassengers: 2500,
      rating: 3.3,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Bayuangga",
      location: "Kota Probolinggo",
      latitude: -7.7656867,
      longitude: 113.175531,
      description: "Terminal Bayuangga di Kota Probolinggo, Indonesia.",
      city: "Kota Probolinggo",
      estimatedPassengers: 4500,
      rating: 3.8,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Tipe B Kepuhsari",
      location: "Jombang",
      latitude: -7.533184,
      longitude: 112.2606544,
      description: "Terminal Tipe B Kepuhsari di Jombang, Indonesia.",
      city: "Jombang",
      estimatedPassengers: 3600,
      rating: 3.6,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Kertajaya",
      location: "Kota Mojokerto",
      latitude: -7.4905548,
      longitude: 112.4485985,
      description: "Terminal Kertajaya di Kota Mojokerto, Indonesia.",
      city: "Kota Mojokerto",
      estimatedPassengers: 3200,
      rating: 3.5,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Kertonegoro",
      location: "Ngawi",
      latitude: -7.4060287,
      longitude: 111.4177864,
      description: "Terminal Kertonegoro di Ngawi, Indonesia.",
      city: "Ngawi",
      estimatedPassengers: 2800,
      rating: 3.3,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Tamanan",
      location: "Kota Kediri",
      latitude: -7.8284354,
      longitude: 111.983848,
      description: "Terminal Tamanan di Kota Kediri, Indonesia.",
      city: "Kota Kediri",
      estimatedPassengers: 4800,
      rating: 3.9,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Hamid Rusdi",
      location: "Kota Malang",
      latitude: -8.0255663,
      longitude: 112.6429881,
      description: "Terminal Hamid Rusdi di Kota Malang, Indonesia.",
      city: "Kota Malang",
      estimatedPassengers: 5200,
      rating: 4.0,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Landungsari",
      location: "Kota Malang",
      latitude: -7.9240658,
      longitude: 112.5988543,
      description: "Terminal Landungsari di Kota Malang, Indonesia.",
      city: "Kota Malang",
      estimatedPassengers: 4100,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Osowilangun",
      location: "Surabaya ",
      latitude: -7.2183207,
      longitude: 112.6515133,
      description: "Terminal Osowilangun di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 6500,
      rating: 4.1,
      type: "A",
      density: "Tinggi"),
  Terminal(
      name: "Terminal Tipe B Anjuk Ladang",
      location: "Nganjuk",
      latitude: -7.5908999,
      longitude: 111.8913261,
      description: "Terminal Tipe B Anjuk Ladang di Nganjuk, Indonesia.",
      city: "Nganjuk",
      estimatedPassengers: 3400,
      rating: 3.6,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Purboyo",
      location: "Kota Madiun",
      latitude: -7.6034212,
      longitude: 111.5340883,
      description: "Terminal Purboyo di Kota Madiun, Indonesia.",
      city: "Kota Madiun",
      estimatedPassengers: 3900,
      rating: 3.8,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Surodakan",
      location: "Trenggalek",
      latitude: -8.0479265,
      longitude: 111.7169235,
      description: "Terminal Surodakan di Trenggalek, Indonesia.",
      city: "Trenggalek",
      estimatedPassengers: 2200,
      rating: 3.3,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kedung Cowek",
      location: "Surabaya ",
      latitude: -7.2121567,
      longitude: 112.7792127,
      description: "Terminal Kedung Cowek di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 5100,
      rating: 3.9,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Untung Suropati",
      location: "Kota Pasuruan",
      latitude: -7.6611945,
      longitude: 112.9281772,
      description: "Terminal Untung Suropati di Kota Pasuruan, Indonesia.",
      city: "Kota Pasuruan",
      estimatedPassengers: 4300,
      rating: 3.8,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Sampang",
      location: "Sampang",
      latitude: -7.1948318,
      longitude: 113.2449133,
      description: "Terminal Sampang di Sampang, Indonesia.",
      city: "Sampang",
      estimatedPassengers: 2800,
      rating: 3.4,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Caruban",
      location: "Mejayan",
      latitude: -7.5478035,
      longitude: 111.6697869,
      description: "Terminal Caruban di Mejayan, Indonesia.",
      city: "Mejayan",
      estimatedPassengers: 2500,
      rating: 3.3,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Maospati",
      location: "Maospati",
      latitude: -7.5962056,
      longitude: 111.4265386,
      description: "Terminal Maospati di Maospati, Indonesia.",
      city: "Maospati",
      estimatedPassengers: 2100,
      rating: 3.2,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Lama Kediri",
      location: "Kota Kediri",
      latitude: -7.8318192,
      longitude: 112.0312368,
      description: "Terminal Lama Kediri di Kota Kediri, Indonesia.",
      city: "Kota Kediri",
      estimatedPassengers: 2000,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Gayatri",
      location: "Karangwaru",
      latitude: -8.0727279,
      longitude: 111.8967137,
      description: "Terminal Gayatri di Karangwaru, Indonesia.",
      city: "Karangwaru",
      estimatedPassengers: 1800,
      rating: 3.1,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Patria",
      location: "Blitar",
      latitude: -8.1241511,
      longitude: 112.1585794,
      description: "Terminal Patria di Blitar, Indonesia.",
      city: "Blitar",
      estimatedPassengers: 4200,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Magetan",
      location: "Magetan",
      latitude: -7.6295173,
      longitude: 111.3296837,
      description: "Terminal Magetan di Magetan, Indonesia.",
      city: "Magetan",
      estimatedPassengers: 2700,
      rating: 3.4,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Bondowoso",
      location: "Demangan",
      latitude: -7.9157963,
      longitude: 113.8313218,
      description: "Terminal Bondowoso di Demangan, Indonesia.",
      city: "Demangan",
      estimatedPassengers: 2900,
      rating: 3.5,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Talangagung",
      location: "Talangagung",
      latitude: -8.1278315,
      longitude: 112.5572626,
      description: "Terminal Talangagung di Talangagung, Indonesia.",
      city: "Talangagung",
      estimatedPassengers: 1700,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Arya Wiraraja",
      location: "Kolor",
      latitude: -7.0284588,
      longitude: 113.8592068,
      description: "Terminal Arya Wiraraja di Kolor, Indonesia.",
      city: "Kolor",
      estimatedPassengers: 3800,
      rating: 3.6,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Seloaji",
      location: "Cekok",
      latitude: -7.8366517,
      longitude: 111.4853684,
      description: "Terminal Seloaji di Cekok, Indonesia.",
      city: "Cekok",
      estimatedPassengers: 1600,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Benowo",
      location: "Surabaya ",
      latitude: -7.2353068,
      longitude: 112.6080796,
      description: "Terminal Benowo di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 3200,
      rating: 3.5,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Terminal Lama",
      location: "Kota Pasuruan",
      latitude: -7.6407566,
      longitude: 112.9138158,
      description: "Terminal Lama di Kota Pasuruan, Indonesia.",
      city: "Kota Pasuruan",
      estimatedPassengers: 1800,
      rating: 2.9,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal angkutan",
      location: "Sitirejo",
      latitude: -8.0257669,
      longitude: 112.6121074,
      description: "Terminal angkutan di Sitirejo, Indonesia.",
      city: "Sitirejo",
      estimatedPassengers: 2100,
      rating: 3.1,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Besuki",
      location: "Besuki",
      latitude: -7.7340387,
      longitude: 113.6921559,
      description: "Terminal Besuki di Besuki, Indonesia.",
      city: "Besuki",
      estimatedPassengers: 1600,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Wonosari",
      location: "Wonosari",
      latitude: -8.0296153,
      longitude: 112.4937225,
      description: "Terminal Wonosari di Wonosari, Indonesia.",
      city: "Wonosari",
      estimatedPassengers: 1900,
      rating: 3.1,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Panggul",
      location: "Wonocoyo",
      latitude: -8.2446113,
      longitude: 111.454326,
      description: "Terminal Panggul di Wonocoyo, Indonesia.",
      city: "Wonocoyo",
      estimatedPassengers: 1400,
      rating: 2.9,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Madyopuro",
      location: "Kota Malang",
      latitude: -7.9742545,
      longitude: 112.6707552,
      description: "Terminal Madyopuro di Kota Malang, Indonesia.",
      city: "Kota Malang",
      estimatedPassengers: 3100,
      rating: 3.5,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Subterminal Bancaran",
      location: "Bancaran",
      latitude: -7.0139814,
      longitude: 112.7600444,
      description: "Subterminal Bancaran di Bancaran, Indonesia.",
      city: "Bancaran",
      estimatedPassengers: 1200,
      rating: 2.8,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kalimas Barat",
      location: "Surabaya ",
      latitude: -7.2226423,
      longitude: 112.7379066,
      description: "Terminal Kalimas Barat di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 3400,
      rating: 3.6,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Terminal Dukuh Kupang",
      location: "Surabaya ",
      latitude: -7.2811238,
      longitude: 112.7116917,
      description: "Terminal Dukuh Kupang di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 4100,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Intermoda Joyoboyo",
      location: "Surabaya ",
      latitude: -7.2992141,
      longitude: 112.7360102,
      description: "Terminal Intermoda Joyoboyo di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 7200,
      rating: 4.2,
      type: "A",
      density: "Tinggi"),
  Terminal(
      name: "Terminal Menanggal",
      location: "Surabaya ",
      latitude: -7.341535,
      longitude: 112.7227653,
      description: "Terminal Menanggal di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 4800,
      rating: 3.9,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Ngrambe",
      location: "Ngawi",
      latitude: -7.5131632,
      longitude: 111.2052639,
      description: "Terminal Ngrambe di Ngawi, Indonesia.",
      city: "Ngawi",
      estimatedPassengers: 1800,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Keputih",
      location: "Surabaya ",
      latitude: -7.2942627,
      longitude: 112.8017041,
      description: "Terminal Keputih di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 2700,
      rating: 3.4,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Balongsari",
      location: "Surabaya ",
      latitude: -7.2589992,
      longitude: 112.6785967,
      description: "Terminal Balongsari di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 3100,
      rating: 3.5,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Terminal Bratang",
      location: "Surabaya ",
      latitude: -7.2985674,
      longitude: 112.7612378,
      description: "Terminal Bratang di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 4900,
      rating: 3.9,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Kenjeran",
      location: "Surabaya ",
      latitude: -7.2410102,
      longitude: 112.7942845,
      description: "Terminal Kenjeran di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 3500,
      rating: 3.6,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Terminal Manukan",
      location: "Surabaya ",
      latitude: -7.2678668,
      longitude: 112.6663129,
      description: "Terminal Manukan di Surabaya , Indonesia.",
      city: "Surabaya ",
      estimatedPassengers: 3200,
      rating: 3.5,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Terminal Bayu Angga",
      location: "Kota Probolinggo",
      latitude: -7.7666519,
      longitude: 113.1744321,
      description: "Terminal Bayu Angga di Kota Probolinggo, Indonesia.",
      city: "Kota Probolinggo",
      estimatedPassengers: 4600,
      rating: 3.8,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Bus Bangkalan",
      location: "Bangkalan",
      latitude: -7.0526058,
      longitude: 112.7327475,
      description: "Terminal Bus Bangkalan di Bangkalan, Indonesia.",
      city: "Bangkalan",
      estimatedPassengers: 3800,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Mulyorejo",
      location: "Kota Malang",
      latitude: -7.9901146,
      longitude: 112.5991993,
      description: "Terminal Mulyorejo di Kota Malang, Indonesia.",
      city: "Kota Malang",
      estimatedPassengers: 2900,
      rating: 3.4,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Blambangan",
      location: "Kelurahan Lateng",
      latitude: -8.2020102,
      longitude: 114.3745502,
      description: "Terminal Blambangan di Kelurahan Lateng, Indonesia.",
      city: "Kelurahan Lateng",
      estimatedPassengers: 4100,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Desa Sarongan",
      location: "Sarongan",
      latitude: -8.5356071,
      longitude: 113.9664508,
      description: "Terminal Desa Sarongan di Sarongan, Indonesia.",
      city: "Sarongan",
      estimatedPassengers: 1200,
      rating: 2.8,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kedungrejo",
      location: "Blambangan",
      latitude: -8.4361235,
      longitude: 114.3184948,
      description: "Terminal Kedungrejo di Blambangan, Indonesia.",
      city: "Blambangan",
      estimatedPassengers: 2400,
      rating: 3.2,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Sukorame",
      location: "Wedoro",
      latitude: -7.3447889,
      longitude: 112.1118998,
      description: "Terminal Sukorame di Wedoro, Indonesia.",
      city: "Wedoro",
      estimatedPassengers: 1700,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Jajag",
      location: "Jajag",
      latitude: -8.4367873,
      longitude: 114.1826204,
      description: "Terminal Jajag di Jajag, Indonesia.",
      city: "Jajag",
      estimatedPassengers: 2200,
      rating: 3.2,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kawedanan",
      location: "Belotan",
      latitude: -7.6818281,
      longitude: 111.4183204,
      description: "Terminal Kawedanan di Belotan, Indonesia.",
      city: "Belotan",
      estimatedPassengers: 1500,
      rating: 2.9,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal SLG",
      location: "Ngasem",
      latitude: -7.8103534,
      longitude: 112.0627951,
      description: "Terminal SLG di Ngasem, Indonesia.",
      city: "Ngasem",
      estimatedPassengers: 1800,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Temayang, Bojonegoro",
      location: "Temayang",
      latitude: -7.3339364,
      longitude: 111.9144805,
      description: "Terminal Temayang, Bojonegoro di Temayang, Indonesia.",
      city: "Temayang",
      estimatedPassengers: 1600,
      rating: 3.0,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Arjasa",
      location: "Jember",
      latitude: -8.1172744,
      longitude: 113.7476121,
      description: "Terminal Arjasa di Jember, Indonesia.",
      city: "Jember",
      estimatedPassengers: 2700,
      rating: 3.3,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Karang Ente",
      location: "Tamansari",
      latitude: -8.2348133,
      longitude: 114.3556055,
      description: "Terminal Karang Ente di Tamansari, Indonesia.",
      city: "Tamansari",
      estimatedPassengers: 1400,
      rating: 2.9,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kota Batu",
      location: "Kota Batu",
      latitude: -7.8821078,
      longitude: 112.5329107,
      description: "Terminal Kota Batu di Kota Batu, Indonesia.",
      city: "Kota Batu",
      estimatedPassengers: 3700,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Pandaan",
      location: "Pandaan",
      latitude: -7.6536201,
      longitude: 112.6888112,
      description: "Terminal Pandaan di Pandaan, Indonesia.",
      city: "Pandaan",
      estimatedPassengers: 3100,
      rating: 3.5,
      type: "C",
      density: "Sedang"),
  Terminal(
      name: "Terminal Bunder",
      location: "Dahanrejo",
      latitude: -7.1702175,
      longitude: 112.5843394,
      description: "Terminal Bunder di Dahanrejo, Indonesia.",
      city: "Dahanrejo",
      estimatedPassengers: 2600,
      rating: 3.3,
      type: "C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Lamongan",
      location: "Lamongan",
      latitude: -7.1109984,
      longitude: 112.4085738,
      description: "Terminal Lamongan di Lamongan, Indonesia.",
      city: "Lamongan",
      estimatedPassengers: 4200,
      rating: 3.7,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Arjosari",
      location: "Kota Malang",
      latitude: -7.9344852,
      longitude: 112.6583971,
      description: "Terminal Arjosari di Kota Malang, Indonesia.",
      city: "Kota Malang",
      estimatedPassengers: 6800,
      rating: 4.1,
      type: "A",
      density: "Tinggi"),
  Terminal(
      name: "Terminal Pare",
      location: "Pare",
      latitude: -7.7469236,
      longitude: 112.2000307,
      description: "Terminal Pare di Pare, Indonesia.",
      city: "Pare",
      estimatedPassengers: 3600,
      rating: 3.6,
      type: "B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Ronggosukowati",
      location: "Pamekasan",
      latitude: -7.1965614,
      longitude: 113.4736652,
      description: "Terminal Ronggosukowati di Pamekasan, Indonesia.",
      city: "Pamekasan",
      estimatedPassengers: 2500,
      rating: 3.7,
      type: "Tipe B",
      density: "Rendah"),
  Terminal(
      name: "Terminal Krian",
      location: "Krian",
      latitude: -7.4113604,
      longitude: 112.5826673,
      description: "Terminal Krian di Krian, Indonesia.",
      city: "Krian",
      estimatedPassengers: 1800,
      rating: 3.4,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Tipe A Pacitan (Zona Merah Grab)",
      location: "Pacitan",
      latitude: -8.2009023,
      longitude: 111.1028726,
      description:
          "Terminal Tipe A Pacitan (Zona Merah Grab) di Pacitan, Indonesia.",
      city: "Pacitan",
      estimatedPassengers: 4500,
      rating: 4.1,
      type: "Tipe A",
      density: "Sedang"),
  Terminal(
      name: "Terminal Larangan",
      location: "Larangan",
      latitude: -7.466635,
      longitude: 112.7124738,
      description: "Terminal Larangan di Larangan, Indonesia.",
      city: "Larangan",
      estimatedPassengers: 1200,
      rating: 3.2,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Sub Terminal Lawangan Daya",
      location: "Pamekasan",
      latitude: -7.1547893,
      longitude: 113.4897778,
      description: "Sub Terminal Lawangan Daya di Pamekasan, Indonesia.",
      city: "Pamekasan",
      estimatedPassengers: 1500,
      rating: 3.0,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Situbondo",
      location: "Situbondo",
      latitude: -7.7066778,
      longitude: 114.0122883,
      description: "Terminal Situbondo di Situbondo, Indonesia.",
      city: "Situbondo",
      estimatedPassengers: 2800,
      rating: 3.5,
      type: "Tipe B",
      density: "Rendah"),
  Terminal(
      name: "Terminal Ambulu",
      location: "Jember",
      latitude: -8.3437022,
      longitude: 113.5930801,
      description: "Terminal Ambulu di Jember, Indonesia.",
      city: "Jember",
      estimatedPassengers: 2200,
      rating: 3.3,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Sub Terminal Mojoagung",
      location: "Mojotrisno",
      latitude: -7.5699161,
      longitude: 112.3518723,
      description: "Sub Terminal Mojoagung di Mojotrisno, Indonesia.",
      city: "Mojotrisno",
      estimatedPassengers: 1700,
      rating: 3.1,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Sub Terminal Slahung",
      location: "Slahung",
      latitude: -8.0328008,
      longitude: 111.4144148,
      description: "Sub Terminal Slahung di Slahung, Indonesia.",
      city: "Slahung",
      estimatedPassengers: 1300,
      rating: 2.9,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Lespadangan",
      location: "Terusan",
      latitude: -7.4573125,
      longitude: 112.4299219,
      description: "Terminal Lespadangan di Terusan, Indonesia.",
      city: "Terusan",
      estimatedPassengers: 1900,
      rating: 3.2,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Banyuangga",
      location: "Kota Probolinggo",
      latitude: -7.767226,
      longitude: 113.1731994,
      description: "Terminal Banyuangga di Kota Probolinggo, Indonesia.",
      city: "Kota Probolinggo",
      estimatedPassengers: 3200,
      rating: 3.8,
      type: "Tipe B",
      density: "Sedang"),
  Terminal(
      name: "Sub Terminal Sidowayah",
      location: "Ngawi",
      latitude: -7.3967408,
      longitude: 111.3367842,
      description: "Sub Terminal Sidowayah di Ngawi, Indonesia.",
      city: "Ngawi",
      estimatedPassengers: 1600,
      rating: 3.0,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kesamben",
      location: "Kesamben",
      latitude: -8.1456776,
      longitude: 112.3664709,
      description: "Kesamben di Kesamben, Indonesia.",
      city: "Kesamben",
      estimatedPassengers: 1400,
      rating: 2.8,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Wiroguno",
      location: "Setail",
      latitude: -8.3585593,
      longitude: 114.1267917,
      description: "Terminal Wiroguno di Setail, Indonesia.",
      city: "Setail",
      estimatedPassengers: 2100,
      rating: 3.3,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Sub Terminal Geneng - Kabupaten Ngawi",
      location: "Ngawi",
      latitude: -7.4948981,
      longitude: 111.4284315,
      description: "Sub Terminal Geneng - Kabupaten Ngawi di Ngawi, Indonesia.",
      city: "Ngawi",
      estimatedPassengers: 1800,
      rating: 3.1,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Tipe B Caruban",
      location: "Mejayan",
      latitude: -7.5482361,
      longitude: 111.6708266,
      description: "Terminal Tipe B Caruban di Mejayan, Indonesia.",
      city: "Mejayan",
      estimatedPassengers: 3500,
      rating: 3.6,
      type: "Tipe B",
      density: "Sedang"),
  Terminal(
      name: "Terminal Jajag",
      location: "Jajag",
      latitude: -8.4371626,
      longitude: 114.1826568,
      description: "Terminal Jajag di Jajag, Indonesia.",
      city: "Jajag",
      estimatedPassengers: 1700,
      rating: 3.0,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Purabaya",
      location: "Kedungrejo",
      latitude: -7.3507901,
      longitude: 112.724726,
      description: "Terminal Purabaya di Kedungrejo, Indonesia.",
      city: "Kedungrejo",
      estimatedPassengers: 7500,
      rating: 4.3,
      type: "Tipe A",
      density: "Tinggi"),
  Terminal(
      name: "Terminal Muncar",
      location: "Blambangan",
      latitude: -8.436507,
      longitude: 114.3183378,
      description: "Terminal Muncar di Blambangan, Indonesia.",
      city: "Blambangan",
      estimatedPassengers: 1900,
      rating: 3.2,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Lorok",
      location: "Lorok",
      latitude: -8.219781,
      longitude: 111.3185958,
      description: "Terminal Lorok di Lorok, Indonesia.",
      city: "Lorok",
      estimatedPassengers: 1400,
      rating: 2.9,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Rogojampi",
      location: "Banyuwangi",
      latitude: -8.3029613,
      longitude: 114.2969872,
      description: "Terminal Rogojampi di Banyuwangi, Indonesia.",
      city: "Banyuwangi",
      estimatedPassengers: 2300,
      rating: 3.4,
      type: "Tipe B",
      density: "Rendah"),
  Terminal(
      name: "Terminal Arjasa",
      location: "Jember",
      latitude: -8.1180522,
      longitude: 113.7479288,
      description: "Terminal Arjasa di Jember, Indonesia.",
      city: "Jember",
      estimatedPassengers: 2000,
      rating: 3.2,
      type: "Tipe C",
      density: "Rendah"),
  Terminal(
      name: "Terminal Kasuari",
      location: "Surabaya",
      latitude: -7.2354104,
      longitude: 112.7363327,
      description: "Terminal Kasuari di Surabaya, Indonesia.",
      city: "Surabaya",
      estimatedPassengers: 5200,
      rating: 3.9,
      type: "Tipe B",
      density: "Sedang"),
  Terminal(
      name: "Bus Terminal Bayangan Gadang",
      location: "Kota Malang",
      latitude: -8.0229593,
      longitude: 112.628126,
      description: "Bus Terminal Bayangan Gadang di Kota Malang, Indonesia.",
      city: "Kota Malang",
      estimatedPassengers: 4800,
      rating: 3.7,
      type: "Tipe B",
      density: "Sedang"),
];
